#----------------------------------------------------------------------------
#       Make Workspace
#
# 
#
# This file was generated by MPC.  Any changes made directly to
# this file will be lost the next time it is generated.
#
# MPC Command:
# /home/chajmart/MPC/mwc.pl -type make
#
#----------------------------------------------------------------------------


all: thetour

depend: thetour-depend

clean generated realclean check-syntax $(CUSTOM_TARGETS):
	@$(MAKE) -f Makefile.thetour $(@)

.PHONY: thetour
thetour:
	@$(MAKE) -f Makefile.thetour all

.PHONY: thetour-depend
thetour-depend:
	@$(MAKE) -f Makefile.thetour depend

project_name_list:
	@echo thetour
